project:
  type: website
  output-dir: docs


website:
  title: "Thahirah"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Projects
      - href: reflection.qmd
        text: Reflection
      - href: hobbies.qmd
        text: Hobbies

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

