project:
  type: website
  output-dir: docs


website:
  title: "Thahirah"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - project.qmd
      - reflection.qmd
      - hobbies.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

